packages:
  - packages/*
  - apps/**
catalog:
  "@eslint/eslintrc": ^3
  "@eslint/js": ^9.34.0
  "@fastify/autoload": ^6.3.1
  "@fastify/cors": ^11.1.0
  "@fastify/helmet": ^13.0.1
  "@fastify/postgres": ^6.0.2
  "@fastify/swagger": ^9.5.1
  "@fastify/swagger-ui": ^5.2.3
  "@nearform/sql": ^1.10.7
  "@tailwindcss/postcss": ^4
  "@tanstack/eslint-plugin-query": ^5.83.1
  "@tanstack/react-query": ^5.85.5
  "@tanstack/react-query-devtools": ^5.85.5
  "@tanstack/react-query-next-experimental": ^5.85.5
  "@types/node": ^24.3.0
  "@types/pg": ^8.15.5
  "@types/react": ^19
  "@types/react-dom": ^19
  "@typescript-eslint/eslint-plugin": ^8.41.0
  "@typescript-eslint/parser": ^8.41.0
  babel-plugin-react-compiler: ^1.0.0
  concurrently: ^8.2.2
  es-toolkit: ^1.39.10
  eslint: ^9.34.0
  eslint-config-next: 15.5.0
  eslint-config-prettier: ^10.1.8
  fastify: ^5.5.0
  fastify-plugin: ^5.1.0
  fastify-type-provider-zod: ^5.0.3
  next: 15.5.0
  next-intl: ^4.3.5
  pg: ^8.16.3
  pino: ^9.9.0
  pino-pretty: ^13.1.1
  postgrator: ^8.0.0
  postgrator-cli: ^9.0.1
  react: 19.1.1
  react-dom: 19.1.1
  react-error-boundary: ^6.0.0
  tailwindcss: ^4
  tsup: ^8.5.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  typescript-eslint: ^8.41.0
  vitest: ^3.2.4
  zod: ^4.1.3
