packages:
  - packages/*
  - apps/**

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.39.1
  '@fastify/autoload': ^6.3.1
  '@fastify/cors': ^11.1.0
  '@fastify/helmet': ^13.0.2
  '@fastify/postgres': ^6.0.2
  '@fastify/swagger': ^9.6.1
  '@fastify/swagger-ui': ^5.2.3
  '@nearform/sql': ^1.10.7
  '@tailwindcss/postcss': ^4.1.17
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/react-query': ^5.90.11
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-query-next-experimental': ^5.91.0
  '@types/node': ^24.10.1
  '@types/pg': ^8.15.6
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.48.0
  '@typescript-eslint/parser': ^8.48.0
  babel-plugin-react-compiler: ^1.0.0
  concurrently: ^9.2.1
  es-toolkit: ^1.42.0
  eslint: ^9.39.1
  eslint-config-next: 16.0.5
  eslint-config-prettier: ^10.1.8
  fastify: ^5.6.2
  fastify-plugin: ^5.1.0
  fastify-type-provider-zod: ^6.1.0
  next: 16.0.5
  next-intl: ^4.5.6
  pg: ^8.16.3
  pino: ^10.1.0
  pino-pretty: ^13.1.2
  postgrator: ^8.0.0
  postgrator-cli: ^9.1.0
  react: 19.2.0
  react-dom: 19.2.0
  react-error-boundary: ^6.0.0
  tailwindcss: ^4.1.17
  tsup: ^8.5.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  typescript-eslint: ^8.48.0
  vitest: ^4.0.14
  zod: ^4.1.13

catalogMode: strict

cleanupUnusedCatalogs: true
