INSERT INTO todos (text) VALUES
('Beyond console.log(): Smarter Logging with Logpoints'),
('Debug code'),
-- ('CSS Shadow Editing'),
('Measure Unused Script & CSS'),
('Emulate Focus'),
('Rendering Behavior'),
('Accessibility Inspection'),
('Capture Node Screenshots'),
('Throttle Network'),
('Override request'),
-- ('Snippets'),
-- ('Mobile Device Simulation'),
('Workspace'),
('AI Assistance'),
('Performance Debugging'),
('MCP server');