INSERT INTO todos (text, created_at) VALUES
('Beyond console.log(): Smarter Logging with Logpoints', NOW()),
('Debug code', NOW() + INTERVAL '1 millisecond'),
-- ('CSS Shadow Editing', NOW() + INTERVAL '2 millisecond'),
('Measure Unused Script & CSS', NOW() + INTERVAL '3 millisecond'),
('Emulate Focus', NOW() + INTERVAL '4 millisecond'),
('Rendering Behavior', NOW() + INTERVAL '5 millisecond'),
('Accessibility Inspection', NOW() + INTERVAL '6 millisecond'),
('Capture Node Screenshots', NOW() + INTERVAL '7 millisecond'),
('Throttle Network', NOW() + INTERVAL '8 millisecond'),
('Override request', NOW() + INTERVAL '9 millisecond'),
-- ('Snippets', NOW() + INTERVAL '10 millisecond'),
-- ('Mobile Device Simulation', NOW() + INTERVAL '11 millisecond'),
('Workspace', NOW() + INTERVAL '12 millisecond'),
('AI Assistance', NOW() + INTERVAL '13 millisecond'),
('Performance Debugging', NOW() + INTERVAL '14 millisecond'),
('MCP server', NOW() + INTERVAL '15 millisecond');